/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthPatientsRouteImport } from './routes/_auth/patients'
import { Route as AuthChatLogsRouteImport } from './routes/_auth/chat-logs'
import { Route as AuthCallLogsRouteImport } from './routes/_auth/call-logs'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthAppointmentsRouteImport } from './routes/_auth/appointments'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsRoute = AuthPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatLogsRoute = AuthChatLogsRouteImport.update({
  id: '/chat-logs',
  path: '/chat-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallLogsRoute = AuthCallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsRoute = AuthAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AuthAppointmentsRoute
  '/calendar': typeof AuthCalendarRoute
  '/call-logs': typeof AuthCallLogsRoute
  '/chat-logs': typeof AuthChatLogsRoute
  '/patients': typeof AuthPatientsRoute
  '/settings': typeof AuthSettingsRoute
  '/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AuthAppointmentsRoute
  '/calendar': typeof AuthCalendarRoute
  '/call-logs': typeof AuthCallLogsRoute
  '/chat-logs': typeof AuthChatLogsRoute
  '/patients': typeof AuthPatientsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/_auth/appointments': typeof AuthAppointmentsRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/call-logs': typeof AuthCallLogsRoute
  '/_auth/chat-logs': typeof AuthChatLogsRoute
  '/_auth/patients': typeof AuthPatientsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/call-logs'
    | '/chat-logs'
    | '/patients'
    | '/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/call-logs'
    | '/chat-logs'
    | '/patients'
    | '/settings'
    | '/'
    | '/admin/users'
  id:
    | '__root__'
    | '/_auth'
    | '/chat'
    | '/login'
    | '/_auth/appointments'
    | '/_auth/calendar'
    | '/_auth/call-logs'
    | '/_auth/chat-logs'
    | '/_auth/patients'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients': {
      id: '/_auth/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthPatientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat-logs': {
      id: '/_auth/chat-logs'
      path: '/chat-logs'
      fullPath: '/chat-logs'
      preLoaderRoute: typeof AuthChatLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/call-logs': {
      id: '/_auth/call-logs'
      path: '/call-logs'
      fullPath: '/call-logs'
      preLoaderRoute: typeof AuthCallLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments': {
      id: '/_auth/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthAppointmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAppointmentsRoute: typeof AuthAppointmentsRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthCallLogsRoute: typeof AuthCallLogsRoute
  AuthChatLogsRoute: typeof AuthChatLogsRoute
  AuthPatientsRoute: typeof AuthPatientsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppointmentsRoute: AuthAppointmentsRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthCallLogsRoute: AuthCallLogsRoute,
  AuthChatLogsRoute: AuthChatLogsRoute,
  AuthPatientsRoute: AuthPatientsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
