/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthPatientsRouteImport } from './routes/_auth/patients'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthAppointmentsRouteImport } from './routes/_auth/appointments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsRoute = AuthPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsRoute = AuthAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AuthAppointmentsRoute
  '/calendar': typeof AuthCalendarRoute
  '/patients': typeof AuthPatientsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/appointments': typeof AuthAppointmentsRoute
  '/calendar': typeof AuthCalendarRoute
  '/patients': typeof AuthPatientsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/appointments': typeof AuthAppointmentsRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/patients': typeof AuthPatientsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/appointments' | '/calendar' | '/patients'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/appointments' | '/calendar' | '/patients' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/appointments'
    | '/_auth/calendar'
    | '/_auth/patients'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients': {
      id: '/_auth/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthPatientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments': {
      id: '/_auth/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthAppointmentsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAppointmentsRoute: typeof AuthAppointmentsRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthPatientsRoute: typeof AuthPatientsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppointmentsRoute: AuthAppointmentsRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthPatientsRoute: AuthPatientsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
